# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Varnish | Configure service init file.'
  become: yes
  template:
    src: '{{ varnish_service_template }}'
    dest: '/etc/systemd/system/varnish.service'
    owner: 'root'
    group: 'root'
    mode: '0655'
  when: 'varnish_service_template | default(None) != None'
  notify:
    - 'reload systemd'
    - 'restart varnish'

- name: 'Varnish | Configure system configuration file.'
  become: yes
  template:
    src: '{{ varnish_system_config_template }}'
    dest: '{{ varnish_system_config_path }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Varnish | Configure ownership of configuration directory.'
  become: yes
  file:
    path: '{{ varnish_config_path }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Varnish | Configure default VCL.'
  become: yes
  template:
    src: '{{ varnish_default_vcl_template }}'
    dest: '{{ varnish_config_path }}/default.vcl'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'varnish_use_default_vcl'
  notify: 'restart varnish'

- name: 'Varnish | Configure secret file.'
  become: yes
  template:
    src: 'secret.j2'
    dest: '{{ varnish_config_path }}/secret'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart varnish'

