# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Varnish | Debian | Install dependencies.'
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'apt-transport-https'
  when: 'ansible_os_family == "Debian"'

- name: 'Varnish | RedHat | Install dependencies.'
  become: yes
  yum:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'yum-utils'
    - 'pygpgme'
  when: 'ansible_os_family == "RedHat"'

- name: 'Varnish | Debian | Update repository key.'
  become: yes
  apt_key:
    url: 'https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey'
    state: 'present'
  when: 'ansible_os_family == "Debian"'

- name: 'Varnish | Debian | Update repository list.'
  become: yes
  apt_repository:
    repo: "deb https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} main"
    state: 'present'
  when: 'ansible_os_family == "Debian"'

- name: 'Varnish | RedHat | Update repository.'
  become: yes
  yum_repository:
    name: 'varnishcache_{{ varnish_packagecloud_repo }}'
    description: 'Varnish Cache packagecloud.io repository.'
    baseurl: 'https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/el/{{ ansible_distribution_major_version|int }}/$basearch'
    repo_gpgcheck: no
    gpgcheck: no
    enabled: yes
    gpgkey: 'https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey'
    sslverify: '1'
    sslcacert: '/etc/pki/tls/certs/ca-bundle.crt'
  register: 'varnish_packagecloud_repo_install'
  when: 'ansible_os_family == "RedHat"'

- name: 'Varnish | RedHat | Refresh metadata cache.'
  command: 'yum clean metadata'
  args:
    warn: no
  when: 'ansible_os_family == "RedHat" and varnish_packagecloud_repo_install.changed'

- name: 'Varnish | Debian | Install Varnish packages.'
  become: yes
  apt:
    name: '{{ item.name if item.version is not defined else item.name + "=" + item.version }}'
    cache_valid_time: '{{ item.cache_valid_time | default(omit) }}'
    deb: '{{ item.deb | default(omit) }}'
    default_release: '{{ item.default_release | default(omit) }}'
    dpkg_options: '{{ item.dpkg_options | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    install_recommends: '{{ item.install_recommends | default(omit) }}'
    purge: '{{ item.purge | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_cache: '{{ item.update_cache | default(omit) }}'
    upgrade: '{{ item.upgrade | default(omit) }}'
  with_items: '{{ varnish_packages }}'
  when: 'ansible_os_family == "Debian"'

- name: 'Varnish | RedHat | Install Varnish packages.'
  become: yes
  yum:
    name: '{{ item.name if item.version is not defined else item.name + "-" + item.version }}'
    conf_file: '{{ item.conf_file | default(omit) }}'
    disable_gpg_check: '{{ item.disable_gpg_check | default(omit) }}'
    disablerepo: '{{ item.disablerepo | default(omit) }}'
    enablerepo: '{{ item.enablerepo | default(omit) }}'
    exclude: '{{ item.exclude | default(omit) }}'
    list: '{{ item.list | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    update_cache: '{{ item.update_cache | default(omit) }}'
  with_items: '{{ varnish_packages }}'
  when: 'ansible_os_family == "RedHat"'